sudo: required

language: go

go:
  - "1.8"
arch:
  - amd64
  - arm64
env:
  - DB_USER=root DB_PASSWORD=test123456 DB_HOST=127.0.0.1 DB_PORT=13306 REDIS_HOST=127.0.0.1 REDIS_PORT=16379 API_PORT=18080 API_HOST=127.0.0.1

services:
  - docker
  
script: 
- ls 
- pwd
- ls -l ../
- mkdir   ../openfalcon 
- cd ../
- ls -l 
- cp -r  /home/travis/gopath/src/github.com/mohneesh-9797/* /home/travis/gopath/src/github.com/openfalcon/
- cd openfalcon
- ls -l 
